[package]
name = "AutomatedReasoning"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
crossterm = "0.27.0"
press-btn-continue = "0.2.0"
rand = "0.8.5"
sorted-list = "0.2.0"
terminal-menu = "3.0.0"
